-- create table items (id bigint generated by default as identity, name varchar(255), primary key (id));

INSERT INTO ITEMS VALUES (1, 'Pink Floyd - Dark Side of the Moon', 'LP');
INSERT INTO ITEMS VALUES (2, 'Clock Machine - Love', 'CD');